// Daily motivation for Consistent Change clients.
//
// There is one quote per day of the year (365 in total). Every client sees the
// same line on a given day, picked by quoteForDate() from the local date.
// These are original lines written for the app, not quotes from famous people,
// so none of them carry an attribution.

export const DAILY_QUOTES: readonly string[] = [
  "New year, same rule: show up. Then show up again tomorrow.",
  "You don't need a perfect plan. You need a plan you'll actually follow.",
  "Motivation gets you started. Discipline gets you through February.",
  "One good session won't change you. Two hundred of them will.",
  "Stop waiting to feel ready. Ready is something you become by starting.",
  "Small wins stack. Stack one today.",
  "The weights don't care about your excuses. Neither should you.",
  "Your future body is built from today's boring choices.",
  "Show up on the days you don't feel like it. Those are the days that count.",
  "Consistency beats intensity every single time.",
  "Do the warm-up. Do the work. Do the cool-down. Go home proud.",
  "You won't always be motivated, so learn to be disciplined.",
  "Sleep is training too. Get to bed.",
  "Water first. Coffee second. Excuses never.",
  "The hardest rep is the one that gets you out the door.",
  "Results are slow. Quitting makes them slower.",
  "Own your choices. Every meal, every rep, every early night.",
  "The gym is where you practise keeping promises to yourself.",
  "Tired is a feeling. Done is a decision.",
  "Progress hides for weeks, then shows up all at once. Keep going.",
  "You're not behind. You're building. Keep laying bricks.",
  "Don't negotiate with the version of you that wants to skip.",
  "A bad workout still beats the one you didn't do.",
  "Make it easy to win today. Pack your bag the night before.",
  "Strong is a habit, not a gift.",
  "Earn the rest day. Then actually rest.",
  "You can't out-train a bad diet. Plan your plate.",
  "Discipline is picking the long game when the short game is louder.",
  "No one is coming to do your push-ups for you.",
  "Every rep is a vote for the person you're becoming.",
  "End the month the way you started it: on time and working.",
  "Cosy is lovely. It just never made anyone stronger.",
  "Do it tired. Do it busy. Do it anyway.",
  "Your body keeps score of every early night. Cash in.",
  "Hard days build the person who handles hard days.",
  "Don't tick the days off. Fill them up.",
  "Protein at every meal. Simple rules win.",
  "The plan works if you work the plan.",
  "Feelings are visitors. Let them come, then get under the bar.",
  "Champions are made in the sessions nobody claps for.",
  "Fall off? Fine. Get back on today, not Monday.",
  "Good form first. Heavy weight later. Ego never.",
  "The work you do when no one is watching shows up when everyone is.",
  "Be the person who does what they said they'd do.",
  "Slow progress is still progress. Standing still is not.",
  "Five minutes of movement beats zero minutes of guilt.",
  "Your mind will quit a hundred times before your body does.",
  "Today's sweat is tomorrow's confidence.",
  "Wishing is free. Results cost reps.",
  "Meal prep is self-respect in a plastic container.",
  "You become what you repeat.",
  "Win the morning and the day gets easier.",
  "Show up messy. Show up late. Just show up.",
  "Recovery isn't lazy. It's where the gains are made.",
  "Every set you finish is proof you're tougher than you think.",
  "Stop asking if you feel like it. Ask if you committed to it.",
  "Patience is a training tool. Use it.",
  "Effort is the one thing fully in your control.",
  "Nobody remembers the session you skipped. Your body does.",
  "Take the stairs. Carry the groceries. Train all day.",
  "Strong mind. Strong body. Same muscle.",
  "Today, be one percent better than yesterday. That's the whole job.",
  "Excuses burn zero calories.",
  "The bar is heavy. So is regret. Pick one.",
  "Build a body that can handle the life you want.",
  "Discipline is doing it when the excitement is long gone.",
  "Lock in. Phone down. Reps up.",
  "Sleep eight, train hard, eat clean, repeat.",
  "Goals point the way. Habits do the walking.",
  "Small steps every day beat giant leaps once a month.",
  "You've survived every hard day so far. Today is no different.",
  "The scale is one number. Your effort is the real story.",
  "Earn your confidence one session at a time.",
  "Don't let one slip turn into a slide.",
  "Hydrate like you mean it.",
  "Mondays don't get special treatment. Neither do Fridays. Train.",
  "Hard work doesn't need an audience.",
  "Make your bed. Make your meals. Make your session.",
  "Every early alarm is a small win. Collect them.",
  "Stop starting over. Just keep going.",
  "Your body can do hard things. Prove it again today.",
  "Plan the week, then trust the plan.",
  "It's not about being the best in the gym. It's about being better than last week.",
  "The grind is quiet. The results are loud.",
  "You're one session away from a better mood.",
  "Train for the person you'll be at sixty.",
  "A bit of stiffness today is your body taking notes.",
  "That shaky last rep? That's the feeling of getting better.",
  "A little bit every day adds up to a lot.",
  "Hold the line when it's boring. Boring builds results.",
  "Food is fuel. Fill the tank properly.",
  "Choose the hard thing on purpose.",
  "You don't have to be extreme. You have to be consistent.",
  "When it burns, that's the bit that changes you.",
  "Rest when you must. Never quit.",
  "Big goals are just small tasks done on repeat.",
  "Leave the gym better than you walked in.",
  "Mental toughness is a skill. Practise it today.",
  "Discipline now, freedom later.",
  "Stay hungry for progress, not for junk.",
  "If it matters, schedule it.",
  "Effort is never wasted. It's stored.",
  "Your only competition is the person in the mirror.",
  "Turn up the volume on your effort, not your excuses.",
  "No shortcuts. Just the long road done well.",
  "Commit to the process and the results will follow.",
  "Make the healthy choice the easy choice. Prep it.",
  "Strength takes time. So does everything worth having.",
  "Breathe. Brace. Lift. Repeat.",
  "Get it done before the day gets in the way.",
  "Some days you push. Some days you just hold your ground. Both count.",
  "Your excuses and your results can't share the same room.",
  "A tired body heals. A quitting mind spreads.",
  "Get to bed on time tonight. Tomorrow's session starts now.",
  "Bad day? Train. Good day? Train. See the pattern?",
  "Don't chase motivation. Build routines.",
  "Nobody drifts into great shape. You steer there.",
  "Every set is a small promise kept.",
  "You have more in the tank than your brain is telling you.",
  "Doubt kills more dreams than failure ever will.",
  "It's not a diet. It's how you eat now.",
  "Show up for yourself like you'd show up for a mate.",
  "One more rep. One more day. One more week.",
  "The fastest way to lose progress is to wait for the perfect moment.",
  "Your body hears everything your mind says. Talk tough.",
  "Grit is just patience with sweat on it.",
  "The work is simple. Doing it every day is the hard part.",
  "Choose progress over perfection.",
  "No zero days. Even a walk counts.",
  "Strong people aren't born. They're built, one session at a time.",
  "The best time to train is when you said you would.",
  "Recovery days are part of the plan, not a break from it.",
  "Respect the process. It's respecting you back.",
  "Feel the fear. Lift the weight.",
  "You're allowed to be tired. You're not allowed to give up.",
  "Discipline is remembering what you want.",
  "Tiny habits, done daily, quietly rebuild a whole life.",
  "Fuel properly or don't complain about feeling flat.",
  "Show the weights who's boss.",
  "Character is built in the last set.",
  "Hard choices, easy life. Easy choices, hard life.",
  "Be stubborn about your goals and flexible about your methods.",
  "You can't fake a deadlift.",
  "A strong week starts with a planned Sunday.",
  "Don't think about the whole mountain. Take the next step.",
  "Getting up early stings for a minute. Missing out stings for months.",
  "Get after it. Nobody is handing it out.",
  "You built the habit of skipping. You can build the habit of showing up.",
  "Let your actions shut up your doubts.",
  "Rest is earned, not stolen.",
  "Eat like you love your body. Train like you respect it.",
  "Stay the course. The course is working.",
  "Alarm off, shoes on, out the door. Easy as that.",
  "Today is a good day to prove yourself right.",
  "Every drop of sweat is a deposit.",
  "Results come to the patient, not the perfect.",
  "Your mindset decides the session before your muscles do.",
  "Quit making deals with yourself. Keep the deal you made.",
  "The goal is not to be perfect. The goal is to not quit.",
  "Get strong enough to carry your own weight in life.",
  "Hunger fades. Habits stay.",
  "Treat every session like it matters. It does.",
  "Consistency is the cheat code.",
  "The mirror changes slowly. Your mind changes first.",
  "Push past the point where you'd normally stop.",
  "Make your future self grateful.",
  "Busy is a reason. It's not an excuse.",
  "You show up. The magic is in the repeat.",
  "Train hard, sleep deep, eat real food.",
  "Make it a non-negotiable.",
  "Halfway through the year. Finish stronger than you started.",
  "Keep going. Your future self is watching.",
  "Short on time? Short session. Never no session.",
  "Belief opens the door. Habits walk you through it.",
  "The weight you lift is the weight you lift off your mind.",
  "Learn to love the boring basics.",
  "Discipline is a muscle. Train it daily.",
  "You don't find time. You make time.",
  "Every healthy meal is a quiet win.",
  "Take the hit. Learn. Go again.",
  "Results love routine.",
  "Push today so tomorrow pushes back less.",
  "Get uncomfortable on purpose so life feels easier by accident.",
  "Your reasons have to be bigger than your excuses.",
  "Patience. Persistence. Protein.",
  "Wet shirt now, big grin in three months.",
  "You'll never walk out of a session wishing you'd stayed home.",
  "Toughness is quiet. It just keeps showing up.",
  "Make the reps clean and the intent strong.",
  "Pick a side: your reasons for skipping or your reasons for starting.",
  "Today's plan: do the work. Tomorrow's plan: same.",
  "Recovery is where the work turns into results.",
  "Remember why you started.",
  "Less chat about the goal. More reps toward it.",
  "Your habits are writing your story. Make it a good one.",
  "Don't break the chain.",
  "A disciplined person doesn't wait for a good mood.",
  "Earn it every day.",
  "Strength is built under load. So is character.",
  "Plan your meals or your cravings will plan them for you.",
  "One step forward is still forward.",
  "You're stronger than your strongest excuse.",
  "Keep your head down and your effort up.",
  "Ownership: no blaming, no complaining, just doing.",
  "If you're going to do it, do it properly.",
  "Lift heavy things. Make good choices. Repeat.",
  "Tough sessions build tough people.",
  "Turn your 'I'll try' into 'I will'.",
  "You can't control results. You control reps.",
  "Today's session is a seed. Water it for months before you judge it.",
  "Sleep is the cheapest supplement there is.",
  "Fit isn't a destination. It's how you live.",
  "Every no to junk is a yes to your goals.",
  "Hard work compounds like interest. Keep investing.",
  "There's always a way. Look for that before you look for a reason.",
  "It's you versus you. Win today.",
  "The gym teaches you that hard things get easier when you keep doing them.",
  "Courage is walking in even when you feel out of place.",
  "Do the unglamorous work now so the fun stuff is possible later.",
  "Most of winning is just not stopping.",
  "Consistent effort, consistent change.",
  "Your habits don't care about your mood. That's why they work.",
  "Make room for rest. Your muscles grow while you sleep.",
  "Want it more than you want the couch.",
  "Momentum is built one day at a time. Don't lose it.",
  "Be honest about your effort. The bar always is.",
  "Hard is not the same as impossible.",
  "Little by little becomes a lot.",
  "Train your mind to go when your body says stop.",
  "Healthy food can taste good. Learn to cook it.",
  "The rep you hate is the one you need.",
  "Doing it when you don't want to is the whole point.",
  "Build the body. Build the mind. Build the life.",
  "Goals live on paper. Discipline drags them into real life.",
  "The person you want to be is on the other side of this set.",
  "Stop scrolling. Start moving.",
  "Your effort today is a gift to tomorrow's you.",
  "Patience isn't waiting. It's working while you wait.",
  "Long days still have room for short workouts.",
  "Strong habits survive weak days.",
  "The pressure you feel is the progress you'll see.",
  "Life gets heavier. Get stronger.",
  "Shake off the bad week. Win the next session.",
  "If you want different, do different.",
  "Every choice is training for something. Choose well.",
  "Grind quietly. Let the results talk.",
  "Rested beats wrecked. Respect your recovery.",
  "Real change is slow, steady and absolutely worth it.",
  "No one owes you results. Go get them.",
  "The first step is always the hardest. Take it.",
  "Soft couches don't build hard work ethic.",
  "Respect your body enough to feed it right.",
  "No gym nearby? Floor, bodyweight, twenty minutes. Sorted.",
  "The good stuff tends to arrive soaked in sweat.",
  "Excuses are easy. Results take work.",
  "Show up on the grey days. That's where the colour comes from.",
  "Trying is fine. Finishing is better. Push to the end.",
  "Train like the next session is the one that changes everything.",
  "Willpower runs out. Systems don't.",
  "Measure progress in months, not mornings.",
  "Fail a rep? Good. Now you know where the edge is.",
  "Choose the version of you that finishes.",
  "Strength isn't just physical. Show it in your choices today.",
  "Some days you just have to make yourself do it.",
  "A walk after dinner is a small win. Take it.",
  "Make your health the priority, not the leftover.",
  "Hard sessions make easy days feel like gifts.",
  "Back yourself. You've done hard things before.",
  "Keep your promises small and keep them every day.",
  "The struggle you're in today is building the strength you need tomorrow.",
  "Be proud of the work, not just the result.",
  "That takeaway lasts ten minutes. Your goal lasts years. Choose.",
  "Nobody cares if you're tired. Do it anyway, then rest.",
  "Your routine is your superpower.",
  "Mindset is everything. Set yours before you set foot in the gym.",
  "Not every day is a PB day. Every day is a show-up day.",
  "Every healthy habit you build is a brick in the wall.",
  "The goal is consistency, not perfection.",
  "A little progress each day adds up to big results.",
  "Eat your veggies. Lift your weights. Get your sleep. No mystery.",
  "Control the controllables.",
  "Let today's effort be tomorrow's warm-up.",
  "Discomfort is the price of growth. Pay it gladly.",
  "Easy sets are a warm-up, not a workout. Go find the hard ones.",
  "You are one decision away from a better day.",
  "Stand tall. You've earned it.",
  "Effort doesn't lie.",
  "Fill your plate with things that grow you.",
  "Don't stop when you're tired. Stop when you're done.",
  "The habit is the hero.",
  "Each session is a chance to beat yesterday.",
  "Lift your standards along with the weights.",
  "Be relentless in pursuit of what you've set out to do.",
  "Talent is nice. Turning up every week is nicer.",
  "Rest. Reset. Go again.",
  "Smart training, steady effort, real results.",
  "When you want to quit, do one more. Then decide.",
  "Your future is built in your daily routine.",
  "Every set you don't skip is a set that counts.",
  "Make sweat your daily habit.",
  "Grit is choosing to keep going when no one would blame you for stopping.",
  "The body follows the mind. Lead it.",
  "Look after your body like you plan to live in it for a long time. You do.",
  "Prep today, win tomorrow.",
  "A strong core starts with a strong commitment.",
  "Show yourself what you're made of.",
  "Don't wait for spring to get going. Start today.",
  "Good habits, built daily, last forever.",
  "Bring your best to the bar today.",
  "Focus on the next rep, not the whole session.",
  "Embrace the grind. It's building you.",
  "Rest is part of the programme. Treat it seriously.",
  "Keep your word to yourself. That's real discipline.",
  "Your progress is proof the work is working.",
  "Make healthy choices boringly consistent.",
  "There's power in showing up when it's hard.",
  "Push the limits. Find new ones.",
  "Stronger every day, one choice at a time.",
  "Plan it. Pack it. Do it.",
  "The snooze button has never built anything. Get up.",
  "Let your effort set the standard.",
  "The bar doesn't lie, and neither does the mirror over time.",
  "Fuel for performance, not for comfort.",
  "Every day is leg day for your mindset.",
  "Hard work today, easier tomorrow.",
  "Never underestimate the power of just turning up.",
  "Small sacrifices now, big rewards later.",
  "Make it count. Every session, every rep.",
  "Rest well tonight. Big things tomorrow.",
  "Toughness is a choice you make every morning.",
  "Ignore the noise. Do the work.",
  "Your goals don't care how you feel. Get moving.",
  "The best project you'll ever work on is you.",
  "Be stronger than the urge to quit.",
  "Every session leaves you a little more capable.",
  "Stick to the plan when the plan gets boring.",
  "Quality reps. Quality meals. Quality sleep.",
  "Don't let a busy week become a lost week.",
  "You don't have to feel good to do good.",
  "Steady wins. Always has.",
  "Think less. Lift more.",
  "Your actions are louder than your intentions.",
  "Turn the music up and the doubt down.",
  "Load-shedding can switch off the lights. It can't switch off your push-ups.",
  "Braai day? Enjoy it. Just pile the salad next to the boerewors.",
  "Heat outside is no excuse. Train early, drink water, crack on.",
  "Bodyweight squats while the kettle boils. Every bit counts.",
  "Your coach can write the plan. Only you can turn up for it.",
  "Track it honestly. The numbers can only help if they're true.",
  "Ask for help when you need it. Then do the work yourself.",
  "Weekends are part of the week. Keep the habits rolling.",
  "Missed a meal plan? The next meal is a fresh chance.",
  "Strong legs, strong lungs, strong head. Build all three.",
  "Count your wins this week, not just your misses.",
  "Your check-in isn't a test. It's a mirror. Be honest with it.",
  "Lights off, phone away, eight hours. That's a training session too.",
  "Finish the year moving. Your January self will thank you.",
  "December still counts. Don't coast into January.",
  "Every day you keep going, the old you loses a little ground.",
  "Strong finish. Same habits. No holiday from yourself.",
  "Enjoy the festive season. Then come back hungry.",
  "Rest, reflect, and get ready to go again.",
  "Look back at how far you've come this year. Now look forward.",
  "Make next year's version of you proud. Start today.",
  "Last day of the year. Finish it the way you want to start the next one.",
];

/**
 * Returns the quote for the given date. Day 1 (1 January) gives the first
 * quote; day 366 in a leap year wraps back to the first one.
 * Uses the local calendar date, so the quote changes at local midnight.
 */
export function quoteForDate(date: Date): string {
  const year = date.getFullYear();
  const startOfYear = new Date(year, 0, 1);
  const localMidnight = new Date(year, date.getMonth(), date.getDate());
  const msPerDay = 24 * 60 * 60 * 1000;
  // Round so a daylight-saving hour can't push the count off by one.
  const dayOfYear =
    Math.round((localMidnight.getTime() - startOfYear.getTime()) / msPerDay) + 1;
  return DAILY_QUOTES[(dayOfYear - 1) % DAILY_QUOTES.length];
}
