// Hand-written mirror of supabase/migrations/0001_init.sql.
// If the schema drifts from this, regenerate with:
//   npx supabase gen types typescript --linked > src/types/database.ts

export type AccessStatus = "active" | "expiring_soon" | "expired";
export type PlanType = "intro_1mo" | "sub_6mo" | "sub_12mo";
export type PackageType = "training_only" | "training_nutrition" | "training_nutrition_lifestyle";
export type HighGiTiming = "before_training" | "before_bed" | "other";
export type ClientStatusFlag = "green" | "orange" | "red";

// Bank details a trainer shows their clients on the payment screen (0029).
// Every field is optional because a new trainer fills them in after signup.
export type EftDetails = {
  account_holder?: string;
  bank?: string;
  account_type?: string;
  branch_code?: string;
  account_number?: string;
};

export type Trainer = {
  id: string;
  name: string;
  email: string;
  // Multi-trainer (0029). A new trainer starts unapproved until the app owner
  // approves them; only the owner's row has is_owner. join_code is what their
  // clients type at signup and is generated by the database.
  approved: boolean;
  is_owner: boolean;
  join_code: string;
  business_name: string | null;
  // Path in the public trainer-logos bucket.
  logo_path: string | null;
  phone: string | null;
  pop_whatsapp: string | null;
  eft_details: EftDetails;
  created_at: string;
}

// What trainer_for_join_code() returns for a valid code (0029).
export type JoinableTrainer = {
  id: string;
  display_name: string;
  logo_path: string | null;
  pop_whatsapp: string | null;
  eft_details: EftDetails;
};

export type Client = {
  id: string;
  trainer_id: string;
  name: string;
  email: string;
  phone: string | null;
  goals: string | null;
  injuries: string | null;
  trainer_notes: string | null;
  intake_responses: Record<string, string>;
  access_status: AccessStatus;
  plan_type: PlanType | null;
  plan_started_at: string | null;
  plan_expires_at: string | null;
  package_type: PackageType | null;
  lifestyle_reset_started_at: string | null;
  consent_accepted_at: string | null;
  privacy_policy_version: string | null;
  status_flag: ClientStatusFlag;
  status_flag_note: string | null;
  status_flag_updated_at: string | null;
  // Storage path in the client-avatars bucket (0026); null until a photo is set.
  avatar_path: string | null;
  // Off by default; only the client can turn it on (0027). While off, the
  // trainer can't see any of their progress photos.
  progress_photos_shared: boolean;
  // Full exercise library (0043). Off by default: the client sees only their
  // own program's exercises until their trainer switches it on.
  library_access: boolean;
  created_at: string;
}

// Private progress photo (0027). Visible to the client, and to the trainer
// only while clients.progress_photos_shared is on.
export type ProgressPhoto = {
  id: string;
  client_id: string;
  storage_path: string;
  taken_on: string;
  // Each update is a set of front, side and back on the same date (0028).
  angle: "front" | "side" | "back";
  created_at: string;
}

// Append-only log of every flag change, written by the trigger in 0023. The
// three status_flag* columns on Client stay the current-state cache; this is the
// history that "Mark as resolved" used to erase.
export type ClientStatusFlagEvent = {
  id: string;
  client_id: string;
  flag: ClientStatusFlag;
  note: string | null;
  set_by: string | null;
  set_by_role: "client" | "trainer" | "system";
  created_at: string;
}

// A trainer's message to one of their clients, usually a reply to a red or
// orange flag (0034). read_at is set by mark_coach_messages_read().
export type CoachMessage = {
  id: string;
  client_id: string;
  trainer_id: string;
  body: string;
  reply_to_flag: ClientStatusFlag | null;
  created_at: string;
  read_at: string | null;
}

// One phone's Expo push token, held by whoever last signed in on it (0034).
export type PushToken = {
  id: string;
  user_id: string;
  expo_push_token: string;
  created_at: string;
}

// The first day of one of the client's periods (0038). Private to her.
export type CycleLog = {
  id: string;
  client_id: string;
  period_start: string;
  created_at: string;
}

export type Checkin = {
  id: string;
  client_id: string;
  checkin_date: string;
  alcohol_units: number;
  sleep_bed_time: string | null;
  sleep_asleep_time: string | null;
  sleep_wake_time: string | null;
  sleep_quality: 1 | 2 | 3 | 4 | 5 | null;
  water_litres: number;
  electrolytes: boolean;
  meals_total: number;
  high_gi_count: number;
  high_gi_timing: HighGiTiming[];
  screen_time_before_bed_minutes: number | null;
  read_non_backlit_device: boolean;
  breathing_or_stretching_done: boolean;
  // Replaced the three questions above in the trimmed check-in. Null on
  // check-ins from before it was asked.
  wound_down: boolean | null;
  distress_flag: boolean;
  distress_notes: string | null;
  created_at: string;
}

export type Video = {
  id: string;
  client_id: string;
  checkin_id: string | null;
  storage_provider: "supabase" | "mux" | "cloudflare_stream";
  storage_path: string;
  playback_url: string | null;
  uploaded_at: string;
  expires_at: string;
  deleted_at: string | null;
}

export type Exercise = {
  id: string;
  name: string;
  category: string | null;
  source: "movekit" | "muscle_and_motion" | "own_library";
  external_url: string | null;
  sort_order: number;
  // No gym machine needed: shown on the Home tab (0045).
  home_friendly: boolean;
}

export type SetEffort = "comfortable" | "close_to_failure" | "failure";

export type WorkoutLog = {
  id: string;
  client_id: string;
  exercise_id: string | null;
  exercise_name: string;
  log_date: string;
  set_number: number;
  weight_kg: number | null;
  reps: number;
  effort: SetEffort;
  created_at: string;
}

export type ProgramKind = "quick" | "weekly" | "custom";

// 0035. trainer_id null = built into the app, usable by every trainer.
export type Program = {
  id: string;
  trainer_id: string | null;
  name: string;
  kind: ProgramKind;
  description: string | null;
  // Weekly programs: index 0 = Monday.
  day_titles: string[];
  // Shown before the first exercise of every session (0048).
  warm_up: string;
  created_at: string;
}

export type ProgramExercise = {
  id: string;
  program_id: string;
  // 1 = Monday ... 7 = Sunday for weekly programs; always 1 otherwise.
  day_number: number;
  sort_order: number;
  exercise_id: string | null;
  exercise_name: string;
  sets: number;
  reps: string;
  rest_seconds: number;
  // A cardio block (0048): exercise_name is the machine or the trainer's own
  // words, reps is how long, e.g. "30 sec".
  kind: "exercise" | "cardio";
}

export type ClientProgram = {
  client_id: string;
  program_id: string;
  started_on: string;
  assigned_at: string;
  // Where the client is up to in a weekly program (0037); null until they
  // first complete or move a session.
  current_day: number | null;
  due_on: string | null;
  last_completed_at: string | null;
}

export type Habit = {
  id: string;
  client_id: string;
  name: string;
  active_days: number[];
  reps_target: number;
  start_date: string;
  end_date: string | null;
  reminder_enabled: boolean;
  reminder_time: string | null;
  created_at: string;
}

export type HabitLog = {
  id: string;
  habit_id: string;
  log_date: string;
  reps_completed: number;
  created_at: string;
}

export type LifestyleResetDailyLog = {
  id: string;
  client_id: string;
  log_date: string;
  morning_daylight: boolean;
  breathing: boolean;
  daily_movement: boolean;
  protein_meals: boolean;
  strength_training: boolean;
  aerobic_exercise: boolean;
  consistent_sleep: boolean;
  evening_winddown: boolean;
  created_at: string;
}

// Suggestion box (0046): anyone can suggest, the app owner reads them all.
export type SuggestionStatus = "new" | "good_idea" | "not_now";

export type Suggestion = {
  id: string;
  author_id: string;
  author_role: "client" | "trainer";
  author_name: string;
  body: string;
  status: SuggestionStatus;
  created_at: string;
};

export interface Database {
  public: {
    Tables: {
      trainers: { Row: Trainer; Insert: Partial<Trainer>; Update: Partial<Trainer>; Relationships: [] };
      clients: { Row: Client; Insert: Partial<Client>; Update: Partial<Client>; Relationships: [] };
      client_status_flag_events: {
        Row: ClientStatusFlagEvent;
        Insert: Partial<ClientStatusFlagEvent>;
        Update: Partial<ClientStatusFlagEvent>;
        Relationships: [];
      };
      coach_messages: {
        Row: CoachMessage;
        Insert: Partial<CoachMessage>;
        Update: Partial<CoachMessage>;
        Relationships: [];
      };
      push_tokens: { Row: PushToken; Insert: Partial<PushToken>; Update: Partial<PushToken>; Relationships: [] };
      cycle_logs: { Row: CycleLog; Insert: Partial<CycleLog>; Update: Partial<CycleLog>; Relationships: [] };
      suggestions: { Row: Suggestion; Insert: Partial<Suggestion>; Update: Partial<Suggestion>; Relationships: [] };
      checkins: { Row: Checkin; Insert: Partial<Checkin>; Update: Partial<Checkin>; Relationships: [] };
      progress_photos: {
        Row: ProgressPhoto;
        Insert: Partial<ProgressPhoto>;
        Update: Partial<ProgressPhoto>;
        Relationships: [];
      };
      videos: { Row: Video; Insert: Partial<Video>; Update: Partial<Video>; Relationships: [] };
      exercises: { Row: Exercise; Insert: Partial<Exercise>; Update: Partial<Exercise>; Relationships: [] };
      habits: { Row: Habit; Insert: Partial<Habit>; Update: Partial<Habit>; Relationships: [] };
      habit_logs: { Row: HabitLog; Insert: Partial<HabitLog>; Update: Partial<HabitLog>; Relationships: [] };
      workout_logs: { Row: WorkoutLog; Insert: Partial<WorkoutLog>; Update: Partial<WorkoutLog>; Relationships: [] };
      programs: { Row: Program; Insert: Partial<Program>; Update: Partial<Program>; Relationships: [] };
      program_exercises: {
        Row: ProgramExercise;
        Insert: Partial<ProgramExercise>;
        Update: Partial<ProgramExercise>;
        Relationships: [];
      };
      client_programs: {
        Row: ClientProgram;
        Insert: Partial<ClientProgram>;
        Update: Partial<ClientProgram>;
        Relationships: [];
      };
      lifestyle_reset_daily_logs: {
        Row: LifestyleResetDailyLog;
        Insert: Partial<LifestyleResetDailyLog>;
        Update: Partial<LifestyleResetDailyLog>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      trainer_for_join_code: {
        Args: { p_code: string };
        Returns: JoinableTrainer[];
      };
      set_my_program_progress: {
        Args: { p_current_day: number; p_due_on: string; p_completed: boolean };
        Returns: undefined;
      };
      mark_coach_messages_read: { Args: Record<string, never>; Returns: undefined };
      register_push_token: { Args: { p_token: string }; Returns: undefined };
      client_monthly_consistency: {
        Args: { p_client_id: string; p_month?: string };
        Returns: { checkin_rate: number; habit_rate: number | null; video_count: number; overall_score: number }[];
      };
    };
  };
}
