-- The full MoveKit library GRIZZ bought and uploaded to the exercise-library
-- bucket on 2026-10-09 (Supabase Pro). Names and body parts come from the
-- file names. Duplicate uploads ("name (1).mp4") are left out, and so is
-- overhead pressing (overhead press, push press, jerks, thrusters and the
-- like), which GRIZZ keeps out of the library as too risky for most clients
-- (docs/exercise-library.md).

-- 1. Videos for the exercises 0039 added without one.
update public.exercises e
set external_url = 'https://vrasgqqubyurzoknsbgm.supabase.co/storage/v1/object/public/exercise-library/' || v.file || '.mp4',
    source = 'movekit'
from (values
  ('Incline Barbell Press', 'barbell-incline-bench-press'),
  ('Flat Dumbbell Press', 'dumbbell-bench-press'),
  ('Machine Chest Press', 'machine-chest-press'),
  ('Cable Fly', 'cable-pec-fly'),
  ('Chest Dip', 'parralel-bar-dips'),
  ('Push-Up', 'push-up'),
  ('Barbell Curl', 'barbell-curl'),
  ('Hammer Curl', 'dumbbell-hammer-curl'),
  ('Incline Dumbbell Curl', 'dumbbell-incline-curl'),
  ('Cable Curl', 'cable-bar-curl'),
  ('Concentration Curl', 'dumbbell-concentration-curl'),
  ('Seated Cable Row', 'machine-seated-cable-row'),
  ('Chest-Supported Row', 'chest-supported-dumbbell-row'),
  ('Close-Grip Lat Pulldown', 'narrow-pulldown'),
  ('Straight-Arm Pulldown', 'straight-arm-lat-pulldown'),
  ('Overhead Dumbbell Extension', 'dumbbell-seated-overhead-tricep-extension'),
  ('Skull Crusher', 'dumbbell-skullcrusher'),
  ('Close-Grip Bench Press', 'barbell-close-grip-bench-press'),
  ('Bench Dip', 'bench-dips'),
  ('Overhead Cable Extension', 'cable-rope-overhead-tricep-extension'),
  ('Tricep Kickback', 'dumbbell-tricep-kickback'),
  ('Leg Press', 'machine-leg-press'),
  ('Hack Squat', 'machine-hack-squat'),
  ('Goblet Squat', 'dumbbell-goblet-squat'),
  ('Step-Up', 'dumbbell-step-up-low'),
  ('Seated Leg Curl', 'seated-leg-curl'),
  ('Hip Thrust', 'barbell-hip-thrust'),
  ('Standing Calf Raise', 'standing-calf-raise-machine'),
  ('Seated Calf Raise', 'seated-calf-raise')
) as v (name, file)
where e.name = v.name and e.external_url is null;

-- 2. Everything else, sorted by body part.
insert into public.exercises (name, category, source, external_url, sort_order)
select v.name, v.category, 'movekit',
  'https://vrasgqqubyurzoknsbgm.supabase.co/storage/v1/object/public/exercise-library/' || v.file,
  v.sort_order
from (values
  ('Barbell Floor Press', 'Push', 'barbell-floor-press.mp4', 100),
  ('Barbell High Incline Bench Press', 'Push', 'barbell-high-incline-bench-press.mp4', 101),
  ('Bodyweight Elevated Push-Up', 'Push', 'bodyweight-elevated-push-up.mp4', 102),
  ('Bodyweight Knee Push-Up', 'Push', 'bodyweight-knee-push-ups.mp4', 103),
  ('Cable Bench Chest Fly', 'Push', 'cable-bench-chest-fly.mp4', 104),
  ('Cable Bench Press', 'Push', 'cable-bench-press.mp4', 105),
  ('Cable Chest Press', 'Push', 'cable-chest-press.mp4', 106),
  ('Cable Decline Bench Press', 'Push', 'cable-decline-bench-press.mp4', 107),
  ('Cable High-to-Low Fly', 'Push', 'cable-high-to-low-fly.mp4', 108),
  ('Cable Incline Bench Press', 'Push', 'cable-incline-bench-press.mp4', 109),
  ('Cable Low-to-High Fly', 'Push', 'cable-low-to-high-fly.mp4', 110),
  ('Cable Standing Single-Arm Chest Press', 'Push', 'cable-standing-single-arm-chest-press.mp4', 111),
  ('Decline Barbell Bench Press', 'Push', 'decline-barbell-bench-press.mp4', 112),
  ('Decline Machine Chest Press', 'Push', 'decline-machine-chest-press.mp4', 113),
  ('Decline Push-Up', 'Push', 'decline-push-up.mp4', 114),
  ('Dumbbell Chest Fly', 'Push', 'dumbbell-chest-fly.mp4', 115),
  ('Dumbbell Decline Bench Press', 'Push', 'dumbbell-decline-bench-press.mp4', 116),
  ('Dumbbell Decline Chest Fly', 'Push', 'dumbbell-decline-chest-fly.mp4', 117),
  ('Dumbbell Incline Chest Fly', 'Push', 'dumbbell-incline-chest-fly.mp4', 118),
  ('Dumbbell Single-Arm Chest Press', 'Push', 'dumbbell-single-arm-chest-press.mp4', 119),
  ('Floor Press', 'Push', 'floor-press.mp4', 120),
  ('Incline Machine Chest Press', 'Push', 'incline-machine-chest-press.mp4', 121),
  ('Incline Push-Up', 'Push', 'incline-push-up.mp4', 122),
  ('Kettlebell Bench Press', 'Push', 'kettlebell-bench-press.mp4', 123),
  ('Kettlebell Incline Bench Press', 'Push', 'kettlebell-incline-bench-press.mp4', 124),
  ('Machine Pec Fly', 'Push', 'machine-pec-fly.mp4', 125),
  ('Neutral-Grip Dumbbell Bench Press', 'Push', 'neutral-grip-dumbbell-bench-press.mp4', 126),
  ('Reverse-Grip Barbell Bench Press', 'Push', 'reverse-grip-barbell-bench-press.mp4', 127),
  ('Single-Arm Cable Fly', 'Push', 'single-arm-cable-fly.mp4', 128),
  ('Smith Machine Bench Press', 'Push', 'smith-machine-bench-press.mp4', 129),
  ('Smith Machine Incline Bench Press', 'Push', 'smith-machine-incline-bench-press.mp4', 130),
  ('Wide-Grip Barbell Bench Press', 'Push', 'wide-grip-barbell-bench-press.mp4', 131),
  ('Band Assisted Pull-Up', 'Pull', 'band-assisted-pull-up.mp4', 132),
  ('Band Kneeling Pulldown', 'Pull', 'band-kneeling-pulldown.mp4', 133),
  ('Band Pullover', 'Pull', 'band-pullover.mp4', 134),
  ('Band Row', 'Pull', 'band-row.mp4', 135),
  ('Band Seated Pulldown', 'Pull', 'band-seated-pulldown.mp4', 136),
  ('Barbell Bent-Over Row', 'Pull', 'barbell-bent-over-row.mp4', 137),
  ('Barbell Pullover', 'Pull', 'barbell-pullover.mp4', 138),
  ('Cable Rope Pullover', 'Pull', 'cable-rope-pullover.mp4', 139),
  ('Cable Row Bar Standing Row', 'Pull', 'cable-row-bar-standing-row.mp4', 140),
  ('Cable Single-Arm Neutral-Grip Row', 'Pull', 'cable-single-arm-neutral-grip-row.mp4', 141),
  ('Cable Single-Arm Underhand-Grip Row', 'Pull', 'cable-single-arm-underhand-grip-row.mp4', 142),
  ('Cable Supinating Row', 'Pull', 'cable-supinating-row.mp4', 143),
  ('Chest-Supported T-Bar Row', 'Pull', 'chest-supported-t-bar-row.mp4', 144),
  ('Chin-Up', 'Pull', 'chin-ups.mp4', 145),
  ('Dumbbell Single-Arm Row', 'Pull', 'dumbbell-single-arm-row.mp4', 146),
  ('Hammer Strength High Row', 'Pull', 'hammer-strength-high-row.mp4', 147),
  ('Hammer Strength Iso-Lateral Row', 'Pull', 'hammer-strength-iso-lateral-row.mp4', 148),
  ('Inverted Row', 'Pull', 'inverted-row.mp4', 149),
  ('Kettlebell Gorilla Row', 'Pull', 'kettlebell-gorilla-row.mp4', 150),
  ('Kettlebell Row', 'Pull', 'kettlebell-row.mp4', 151),
  ('Kettlebell Row (Single Arm)', 'Pull', 'kettlebell-row-single.mp4', 152),
  ('Kettlebell Single-Arm Row', 'Pull', 'kettlebell-single-arm-row.mp4', 153),
  ('Landmine T-Bar Row', 'Pull', 'landmine-t-bar-rows.mp4', 154),
  ('Machine Assisted Pull-Up', 'Pull', 'machine-assisted-pull-up.mp4', 155),
  ('Machine Lat Pullover', 'Pull', 'machine-lat-pullover.mp4', 156),
  ('Machine Neutral Row', 'Pull', 'machine-neutral-row.mp4', 157),
  ('Machine Plate-Loaded T-Bar Row', 'Pull', 'machine-plate-loaded-t-bar-row.mp4', 158),
  ('Machine Pulldown', 'Pull', 'machine-pulldown.mp4', 159),
  ('Machine Underhand Row', 'Pull', 'machine-underhand-row.mp4', 160),
  ('Meadows Row', 'Pull', 'meadows-row.mp4', 161),
  ('Neutral-Grip Lat Pulldown', 'Pull', 'neutral-grip-lat-pulldown.mp4', 162),
  ('Neutral-Grip Pull-Up', 'Pull', 'neutral-grip-pull-up.mp4', 163),
  ('Pendlay Row', 'Pull', 'pendlay-row.mp4', 164),
  ('Seal Row', 'Pull', 'seal-row.mp4', 165),
  ('Single-Arm Dumbbell Row (Unilateral)', 'Pull', 'dumbbell-row-unilateral.mp4', 166),
  ('Single-Arm Lat Pulldown', 'Pull', 'single-arm-lat-pulldown.mp4', 167),
  ('Smith Machine Bent-Over Row', 'Pull', 'smith-machine-bent-over-row.mp4', 168),
  ('Underhand Barbell Row', 'Pull', 'underhand-barbell-row.mp4', 169),
  ('Weighted Pull-Up', 'Pull', 'weighted-pull-ups.mp4', 170),
  ('Wide-Grip Lat Pulldown', 'Pull', 'wide-grip-lat-pulldown.mp4', 171),
  ('Wide-Grip Pull-Up', 'Pull', 'wide-grip-pull-up.mp4', 172),
  ('Wide-Grip Seated Cable Row', 'Pull', 'wide-grip-seated-cable-row.mp4', 173),
  ('Yates Row', 'Pull', 'yates-row.mp4', 174),
  ('Band External Rotation', 'Shoulders', 'band-external-rotation.mp4', 175),
  ('Band High Face Pull', 'Shoulders', 'band-high-face-pull.mp4', 176),
  ('Band Lateral Raise', 'Shoulders', 'band-lateral-raise.mp4', 177),
  ('Band Single-Arm Lateral Raise', 'Shoulders', 'band-single-arm-lateral-raise.mp4', 178),
  ('Cable Bar Face Pull', 'Shoulders', 'cable-bar-face-pull.mp4', 179),
  ('Cable External Rotation', 'Shoulders', 'cable-external-rotation.mp4', 180),
  ('Cable Front Raise', 'Shoulders', 'cable-front-raise.mp4', 181),
  ('Cable Low Single-Arm Lateral Raise', 'Shoulders', 'cable-low-single-arm-lateral-raise.mp4', 182),
  ('Cable Rope Kneeling Face Pull', 'Shoulders', 'cable-rope-kneeling-face-pull.mp4', 183),
  ('Cable Seated Rope Face Pull', 'Shoulders', 'cable-seated-rope-face-pull.mp4', 184),
  ('Dumbbell Front Raise', 'Shoulders', 'dumbbell-front-raise.mp4', 185),
  ('Dumbbell Incline Front Raise', 'Shoulders', 'dumbbell-incline-front-raise.mp4', 186),
  ('Dumbbell Lying Reverse Fly', 'Shoulders', 'dumbbell-laying-reverse-fly.mp4', 187),
  ('Dumbbell Rear-Delt Fly', 'Shoulders', 'dumbbell-rear-delt-fly.mp4', 188),
  ('Dumbbell Seated Rear-Delt Fly', 'Shoulders', 'dumbbell-seated-rear-delt-fly.mp4', 189),
  ('Kettlebell Front Raise', 'Shoulders', 'kettlebell-front-raise.mp4', 190),
  ('Landmine Press', 'Shoulders', 'landmine-press.mp4', 191),
  ('Leaning Cable Lateral Raise', 'Shoulders', 'leaning-cable-lateral-raise.mp4', 192),
  ('Machine Face Pull', 'Shoulders', 'machine-face-pulls.mp4', 193),
  ('Machine Lateral Raise', 'Shoulders', 'machine-lateral-raise.mp4', 194),
  ('Plate Front Raise', 'Shoulders', 'plate-front-raise.mp4', 195),
  ('Reverse Pec Deck', 'Shoulders', 'reverse-pec-deck.mp4', 196),
  ('Single-Arm Landmine Press', 'Shoulders', 'single-arm-landmine-press.mp4', 197),
  ('Band Curl', 'Biceps', 'band-curl.mp4', 198),
  ('Barbell Drag Curl', 'Biceps', 'barbell-drag-curl.mp4', 199),
  ('Bayesian Curl', 'Biceps', 'bayesian-curl.mp4', 200),
  ('Cable Rope Hammer Curl', 'Biceps', 'cable-rope-hammer-curl.mp4', 201),
  ('Close-Grip Barbell Curl', 'Biceps', 'close-grip-barbell-curl.mp4', 202),
  ('Cross-Body Hammer Curl', 'Biceps', 'cross-body-hammer-curl.mp4', 203),
  ('Dumbbell Curl', 'Biceps', 'dumbbell-curl.mp4', 204),
  ('Dumbbell Incline Hammer Curl', 'Biceps', 'dumbbell-incline-hammer-curl.mp4', 205),
  ('Dumbbell Preacher Curl', 'Biceps', 'dumbbell-preacher-curl.mp4', 206),
  ('Dumbbell Standing Single-Arm Curl', 'Biceps', 'dumbbell-standing-single-arm-curl.mp4', 207),
  ('Dumbbell Standing Single-Arm Hammer Curl', 'Biceps', 'dumbbell-standing-single-arm-hammer-curl.mp4', 208),
  ('EZ-Bar Reverse Preacher Curl', 'Biceps', 'ez-bar-reverse-preacher-curl.mp4', 209),
  ('Kettlebell Curl', 'Biceps', 'kettlebell-curl.mp4', 210),
  ('Kettlebell Goblet Curl', 'Biceps', 'kettlebell-goblet-curl.mp4', 211),
  ('Machine Preacher Curl', 'Biceps', 'machine-preacher-curl.mp4', 212),
  ('Reverse-Grip Barbell Curl', 'Biceps', 'reverse-grip-barbell-curl.mp4', 213),
  ('Spider Curl', 'Biceps', 'spider-curl.mp4', 214),
  ('Wide-Grip Barbell Curl', 'Biceps', 'wide-grip-barbell-curl.mp4', 215),
  ('Zottman Curl', 'Biceps', 'zottman-curl.mp4', 216),
  ('Cable Bar Pushdown', 'Triceps', 'cable-bar-pushdown.mp4', 217),
  ('Cable Single-Arm Rope Pushdown', 'Triceps', 'cable-single-arm-rope-pushdown.mp4', 218),
  ('Diamond Push-Up', 'Triceps', 'diamond-push-ups.mp4', 219),
  ('Dumbbell Decline Skull Crusher', 'Triceps', 'dumbbell-decline-skullcrusher.mp4', 220),
  ('JM Press', 'Triceps', 'jm-press.mp4', 221),
  ('Machine Dip', 'Triceps', 'machine-dips.mp4', 222),
  ('Machine Tricep Extension', 'Triceps', 'machine-tricep-extension.mp4', 223),
  ('Single-Arm Overhead Cable Extension', 'Triceps', 'single-arm-overhead-cable-extension.mp4', 224),
  ('Single-Arm Tricep Extension', 'Triceps', 'single-arm-tricep-extension.mp4', 225),
  ('Smith Machine Close-Grip Bench Press', 'Triceps', 'smith-machine-close-grip-bench-press.mp4', 226),
  ('Tate Press', 'Triceps', 'tate-press.mp4', 227),
  ('V-Bar Cable Pushdown', 'Triceps', 'machine-cable-v-bar-push-downs.mp4', 228),
  ('Band Squat', 'Legs', 'band-squat.mp4', 229),
  ('Barbell Banded Back Squat', 'Legs', 'barbell-banded-back-squat.mp4', 230),
  ('Barbell Front Rack Step-Up Knee Drive', 'Legs', 'barbell-front-rack-step-up-knee-drive.mp4', 231),
  ('Barbell Reverse Lunge', 'Legs', 'barbell-reverse-lunge.mp4', 232),
  ('Barbell Split Squat', 'Legs', 'barbell-split-squat.mp4', 233),
  ('Barbell Step-Up Knee Drive', 'Legs', 'barbell-step-up-knee-drive.mp4', 234),
  ('Belt Squat', 'Legs', 'belt-squat.mp4', 235),
  ('Bodyweight Alternating Lateral Lunge', 'Legs', 'bodyweight-alternating-lateral-lunge.mp4', 236),
  ('Bodyweight Alternating Reverse Lunge', 'Legs', 'bodyweight-alternating-reverse-lunges.mp4', 237),
  ('Bodyweight Box Squat', 'Legs', 'bodyweight-box-squat.mp4', 238),
  ('Bodyweight Reverse Lunge', 'Legs', 'bodyweight-reverse-lunge.mp4', 239),
  ('Bodyweight Squat', 'Legs', 'bodyweight-squat.mp4', 240),
  ('Box Jump', 'Legs', 'box-jump.mp4', 241),
  ('Cossack Squat', 'Legs', 'cossack-squat.mp4', 242),
  ('Dumbbell Alternating Forward Lunge', 'Legs', 'dumbbell-alternating-forward-lunge.mp4', 243),
  ('Dumbbell Bulgarian Split Squat', 'Legs', 'dumbbell-bulgarian-split-squat.mp4', 244),
  ('Dumbbell Cossack Squat', 'Legs', 'dumbbell-cossack-squat.mp4', 245),
  ('Dumbbell Front Squat', 'Legs', 'dumbbell-front-squat.mp4', 246),
  ('Dumbbell Front Squat (Tempo)', 'Legs', 'dumbbell-front-squat-tempo.mp4', 247),
  ('Dumbbell Goblet Alternating Curtsy Lunge', 'Legs', 'dumbbell-goblet-alternating-curtsy-lunge.mp4', 248),
  ('Dumbbell Goblet Bulgarian Split Squat', 'Legs', 'dumbbell-goblet-bulgarian-split-squat.mp4', 249),
  ('Dumbbell Goblet Forward Lunge', 'Legs', 'dumbbell-goblet-forward-lunge.mp4', 250),
  ('Dumbbell Goblet Reverse Lunge', 'Legs', 'dumbbell-goblet-reverse-lunge.mp4', 251),
  ('Dumbbell Goblet Split Squat', 'Legs', 'dumbbell-goblet-split-squat.mp4', 252),
  ('Dumbbell Lateral Lunge', 'Legs', 'dumbbell-lateral-lunge.mp4', 253),
  ('Dumbbell Sumo Squat', 'Legs', 'dumbbell-sumo-squat.mp4', 254),
  ('Forward Lunge', 'Legs', 'forward-lunge.mp4', 255),
  ('Front Squat', 'Legs', 'front-squat.mp4', 256),
  ('Front-Foot-Elevated Split Squat', 'Legs', 'front-foot-elevated-split-squat.mp4', 257),
  ('Jump Squat', 'Legs', 'jump-squats.mp4', 258),
  ('Kettlebell Alternating Curtsy Lunge', 'Legs', 'kettlebell-alternating-curtsy-lunge.mp4', 259),
  ('Kettlebell Assisted Bulgarian Split Squat', 'Legs', 'kettlebell-assisted-bulgarian-split-squat.mp4', 260),
  ('Kettlebell Goblet Squat', 'Legs', 'kettlebell-goblet-squat.mp4', 261),
  ('Machine Horizontal Leg Press', 'Legs', 'machine-horizontal-leg-press.mp4', 262),
  ('Pause Squat', 'Legs', 'pause-squat.mp4', 263),
  ('Pendulum Squat (V-Squat)', 'Legs', 'pendulum-squat-v-squat.mp4', 264),
  ('Plate Forward Lunge', 'Legs', 'plate-forward-lunge.mp4', 265),
  ('Reverse Hack Squat', 'Legs', 'reverse-hack-squat.mp4', 266),
  ('Single-Leg Press', 'Legs', 'single-leg-press.mp4', 267),
  ('Single-Leg Step-Down', 'Legs', 'single-leg-step-down.mp4', 268),
  ('Smith Machine Front Squat', 'Legs', 'smith-machine-front-squat.mp4', 269),
  ('Smith Machine Squat', 'Legs', 'smith-machine-squat.mp4', 270),
  ('Split Squat Isometric Hold', 'Legs', 'split-squat-isometric-hold.mp4', 271),
  ('Wall Sit', 'Legs', 'wall-sit.mp4', 272),
  ('Zercher Squat', 'Legs', 'zercher-squat.mp4', 273),
  ('Machine Plate-Loaded Leg Extension', 'Quads', 'machine-plate-loaded-leg-extension.mp4', 274),
  ('Sissy Squat', 'Quads', 'sissy-squat.mp4', 275),
  ('Band Leg Curl', 'Hamstrings', 'band-leg-curl.mp4', 276),
  ('Cable Single-Leg Lying Leg Curl', 'Hamstrings', 'cable-single-leg-laying-leg-curl.mp4', 277),
  ('Dumbbell Leg Curl', 'Hamstrings', 'dumbbell-leg-curl.mp4', 278),
  ('Good Morning', 'Hamstrings', 'good-mornings.mp4', 279),
  ('Hamstring Curl', 'Hamstrings', 'hamstring-curl.mp4', 280),
  ('Nordic Hamstring Curl', 'Hamstrings', 'nordic-hamstring-curl.mp4', 281),
  ('Romanian Deadlift Hamstring Sweeps', 'Hamstrings', 'romanian-deadlift-hamstring-sweeps.mp4', 282),
  ('Stability Ball Leg Curl', 'Hamstrings', 'stability-ball-leg-curl.mp4', 283),
  ('Towel Slide Leg Curl', 'Hamstrings', 'towel-slide-leg-curl.mp4', 284),
  ('B-Stance Hip Thrust', 'Glutes', 'b-stance-hip-thrust.mp4', 285),
  ('Band Glute Bridge', 'Glutes', 'band-glute-bridge.mp4', 286),
  ('Band Hip Abduction', 'Glutes', 'band-hip-abduction.mp4', 287),
  ('Bodyweight Hip Abduction', 'Glutes', 'bodyweight-hip-abduction.mp4', 288),
  ('Cable Bench Straight-Leg Kickback', 'Glutes', 'cable-bench-straight-leg-kickback.mp4', 289),
  ('Cable Hip Abduction', 'Glutes', 'cable-hip-abduction.mp4', 290),
  ('Cable Kickback', 'Glutes', 'cable-kickback.mp4', 291),
  ('Cable Pull Through', 'Glutes', 'cable-pull-through.mp4', 292),
  ('Dumbbell Feet-Elevated Glute Bridge', 'Glutes', 'dumbbell-feet-elevated-glute-bridge.mp4', 293),
  ('Dumbbell Figure Four Heels-Elevated Hip Thrust', 'Glutes', 'dumbbell-figure-four-heels-elevated-hip-thrust.mp4', 294),
  ('Dumbbell Heels-Elevated Hip Thrust', 'Glutes', 'dumbbell-heels-elevated-hip-thrust.mp4', 295),
  ('Dumbbell Single-Leg Hip Thrust', 'Glutes', 'dumbbell-single-leg-hip-thrust.mp4', 296),
  ('Frog Pump', 'Glutes', 'frog-pump.mp4', 297),
  ('Glute Bridge', 'Glutes', 'glute-bridge.mp4', 298),
  ('Glute Kickback Machine', 'Glutes', 'glute-kickback-machine.mp4', 299),
  ('Kettlebell Hip Thrust', 'Glutes', 'kettlebell-hip-thrust.mp4', 300),
  ('Machine Hip Thrust', 'Glutes', 'machine-hip-thrust.mp4', 301),
  ('Reverse Hyperextension', 'Glutes', 'reverse-hyperextension.mp4', 302),
  ('Single-Leg Glute Bridge', 'Glutes', 'single-leg-glute-bridge.mp4', 303),
  ('Single-Leg Hip Thrust', 'Glutes', 'single-leg-hip-thrust.mp4', 304),
  ('Standing Cable Hip Abduction', 'Glutes', 'standing-cable-hip-abduction.mp4', 305),
  ('Bodyweight Donkey Calf Raise', 'Calves', 'bodyweight-donkey-calf-raise.mp4', 306),
  ('Dumbbell Single-Leg Calf Raise', 'Calves', 'dumbbell-single-leg-calf-raise.mp4', 307),
  ('Horizontal Leg Press Calf Press', 'Calves', 'horizontal-leg-press-calf-press.mp4', 308),
  ('Kettlebell Calf Raise', 'Calves', 'kettlebell-calf-raise.mp4', 309),
  ('Single-Leg Standing Calf Raise', 'Calves', 'single-leg-standing-calf-raise.mp4', 310),
  ('Smith Machine Calf Raise', 'Calves', 'smith-machine-calf-raise.mp4', 311),
  ('Tibialis Raise', 'Calves', 'tibialis-raise.mp4', 312),
  ('Back Extension', 'Posterior Chain', 'back-extension.mp4', 313),
  ('Band Romanian Deadlift', 'Posterior Chain', 'band-romanian-deadlift.mp4', 314),
  ('Barbell Rack Pull', 'Posterior Chain', 'barbell-rack-pull.mp4', 315),
  ('Barbell Stiff-Leg Deadlift', 'Posterior Chain', 'barbell-stiff-leg-deadlifts.mp4', 316),
  ('Bodyweight Deadlift', 'Posterior Chain', 'bodyweight-deadlift.mp4', 317),
  ('Deficit Deadlift', 'Posterior Chain', 'deficit-deadlift.mp4', 318),
  ('Deficit Dumbbell Romanian Deadlift', 'Posterior Chain', 'deficit-dumbbell-romanian-deadlift.mp4', 319),
  ('Dumbbell Back Extension', 'Posterior Chain', 'dumbbell-back-extension.mp4', 320),
  ('Dumbbell Cross-Body Romanian Deadlift', 'Posterior Chain', 'dumbbell-cross-body-romanian-deadlift.mp4', 321),
  ('Dumbbell Deadlift', 'Posterior Chain', 'dumbbell-deadlift.mp4', 322),
  ('Hip-Hinge Speed Romanian Deadlift', 'Posterior Chain', 'hip-hinge-speed-romanian-deadlift.mp4', 323),
  ('Kettlebell Romanian Deadlift', 'Posterior Chain', 'kettlebell-romanian-deadlift.mp4', 324),
  ('Kettlebell Sumo Deadlift', 'Posterior Chain', 'kettlebell-sumo-deadlift.mp4', 325),
  ('Kickstand Dumbbell Romanian Deadlift', 'Posterior Chain', 'kickstand-dumbbell-romanian-deadlift.mp4', 326),
  ('Machine 45-Degree Back Extension', 'Posterior Chain', 'machine-45-degree-back-extension.mp4', 327),
  ('Single-Leg Back Extension', 'Posterior Chain', 'single-leg-back-extension.mp4', 328),
  ('Single-Leg Dumbbell Romanian Deadlift', 'Posterior Chain', 'single-leg-dumbbell-romanian-deadlift.mp4', 329),
  ('Single-Leg Kettlebell Romanian Deadlift (Deficit)', 'Posterior Chain', 'single-leg-kettlebell-romanian-deadlift-deficit.mp4', 330),
  ('Single-Leg Romanian Deadlift', 'Posterior Chain', 'single-legged-romanian-deadlifts.mp4', 331),
  ('Smith Machine Sumo Romanian Deadlift', 'Posterior Chain', 'smith-machine-sumo-romanian-deadlift.mp4', 332),
  ('Trap Bar Deadlift', 'Posterior Chain', 'trap-bar-deadlift.mp4', 333),
  ('Band Wood Chopper', 'Core', 'band-wood-chopper.mp4', 334),
  ('Bird Dog', 'Core', 'bird-dog.mp4', 335),
  ('Bodyweight Russian Twist', 'Core', 'bodyweight-russian-twist.mp4', 336),
  ('Cable Side Bend', 'Core', 'cable-side-bend.mp4', 337),
  ('Cable Standing Low-to-High Wood Chopper', 'Core', 'cable-standing-low-to-high-wood-chopper.mp4', 338),
  ('Cable Wood Chopper', 'Core', 'cable-wood-chopper.mp4', 339),
  ('Captain''s Chair Knee Raise', 'Core', 'captains-chair-knee-raise.mp4', 340),
  ('Dead Bug', 'Core', 'dead-bug.mp4', 341),
  ('Decline Crunch', 'Core', 'decline-crunch.mp4', 342),
  ('Decline Sit-Up', 'Core', 'decline-sit-up.mp4', 343),
  ('Dumbbell Russian Twist', 'Core', 'dumbbell-russian-twist.mp4', 344),
  ('Dumbbell Side Bend', 'Core', 'dumbbell-side-bend.mp4', 345),
  ('Dumbbell Sit-Up', 'Core', 'dumbbell-situp.mp4', 346),
  ('Dumbbell Superman', 'Core', 'dumbbell-superman.mp4', 347),
  ('Elbow Side Plank', 'Core', 'elbow-side-plank.mp4', 348),
  ('Hand Plank', 'Core', 'hand-plank.mp4', 349),
  ('Hanging Knee Raise', 'Core', 'hanging-knee-raises.mp4', 350),
  ('Kettlebell Windmill', 'Core', 'kettlebell-windmill.mp4', 351),
  ('Kneeling Cable Crunch', 'Core', 'kneeling-cable-crunch.mp4', 352),
  ('Machine Crunch', 'Core', 'machine-crunch.mp4', 353),
  ('Pallof Press', 'Core', 'pallof-press.mp4', 354),
  ('Superman', 'Core', 'supermans.mp4', 355),
  ('Toes-to-Bar', 'Core', 'toes-to-bar.mp4', 356),
  ('V-Up', 'Core', 'v-up.mp4', 357),
  ('Band Shrug', 'Traps', 'band-shrug.mp4', 358),
  ('Barbell Behind-the-Back 30-Degree Shrug', 'Traps', 'barbell-behind-the-back-30-degree-shrug.mp4', 359),
  ('Barbell Shrug', 'Traps', 'barbell-shrug.mp4', 360),
  ('Barbell Upright Row', 'Traps', 'barbell-upright-row.mp4', 361),
  ('Cable 30-Degree Shrug', 'Traps', 'cable-30-degree-shrug.mp4', 362),
  ('Dumbbell Seated Shrug', 'Traps', 'dumbbell-seated-shrug.mp4', 363),
  ('Dumbbell Shrug', 'Traps', 'dumbbell-shrug.mp4', 364),
  ('Dumbbell Upright Row', 'Traps', 'dumbbell-upright-row.mp4', 365),
  ('Kettlebell Shrug', 'Traps', 'kettlebell-shrug.mp4', 366),
  ('Smith Machine Standing Shrug', 'Traps', 'smith-machine-standing-shrugs.mp4', 367),
  ('Trap Bar Shrug', 'Traps', 'trap-bar-shrug.mp4', 368),
  ('Barbell Wrist Curl', 'Forearms & Grip', 'barbell-wrist-curl.mp4', 369),
  ('Cable Wrist Curl', 'Forearms & Grip', 'cable-wrist-curl.mp4', 370),
  ('Dumbbell Wrist Curl', 'Forearms & Grip', 'dumbbell-wrist-curl.mp4', 371),
  ('Dumbbell Wrist Extension', 'Forearms & Grip', 'dumbbell-wrist-extension.mp4', 372),
  ('Kettlebell Farmer''s Carry', 'Forearms & Grip', 'kettlebell-farmers-carry.mp4', 373),
  ('Plate Pinch', 'Forearms & Grip', 'plate-pinch.mp4', 374),
  ('Wrist Roller', 'Forearms & Grip', 'wrist-roller.mp4', 375),
  ('Neck Curl', 'Neck', 'neck-curl.mp4', 376),
  ('Neck Extension', 'Neck', 'neck-extension.mp4', 377),
  ('Barbell Muscle Snatch', 'Full Body', 'barbell-muscle-snatch.mp4', 378),
  ('Barbell Power Snatch', 'Full Body', 'barbell-power-snatch.mp4', 379),
  ('Barbell Snatch', 'Full Body', 'barbell-snatch.mp4', 380),
  ('Hang Clean', 'Full Body', 'hang-clean.mp4', 381),
  ('Hang Power Clean', 'Full Body', 'hang-power-clean.mp4', 382),
  ('Hang Snatch', 'Full Body', 'hang-snatch.mp4', 383),
  ('Kettlebell Swing', 'Full Body', 'kettlebell-swing.mp4', 384),
  ('Kettlebell Turkish Get-Up', 'Full Body', 'kettlebell-turkish-get-up.mp4', 385),
  ('Power Clean', 'Full Body', 'power-clean.mp4', 386),
  ('Snatch Grip Deadlift', 'Full Body', 'snatch-grip-deadlift.mp4', 387),
  ('Snatch Grip High Pull', 'Full Body', 'snatch-grip-high-pull.mp4', 388),
  ('Snatch Pull', 'Full Body', 'snatch-pull.mp4', 389),
  ('Wall Ball', 'Full Body', 'wall-ball.mp4', 390),
  ('Arc Trainer', 'Cardio', 'arc-trainer.mp4', 391),
  ('Assault Bike', 'Cardio', 'assault-bike.mp4', 392),
  ('Backstroke Swim', 'Cardio', 'backstroke-swim.mp4', 393),
  ('Battle Ropes', 'Cardio', 'battle-ropes.mp4', 394),
  ('Breaststroke Swim', 'Cardio', 'breaststroke-swim.mp4', 395),
  ('Burpee', 'Cardio', 'burpee.mp4', 396),
  ('Butterfly Swim', 'Cardio', 'butterfly-swim.mp4', 397),
  ('Cycling Cool-Down', 'Cardio', 'cycling-cooldown.mp4', 398),
  ('Cycling Intervals', 'Cardio', 'cycling-intervals.mp4', 399),
  ('Cycling Sprint', 'Cardio', 'cycling-sprint.mp4', 400),
  ('Cycling Warm-Up', 'Cardio', 'cycling-warmup.mp4', 401),
  ('Elliptical', 'Cardio', 'elliptical.mp4', 402),
  ('Freestyle Swim', 'Cardio', 'freestyle-swim.mp4', 403),
  ('Hiking', 'Cardio', 'hiking.mp4', 404),
  ('Hill Climb Repeats', 'Cardio', 'hill-climb-repeats.mp4', 405),
  ('Incline Treadmill Walk', 'Cardio', 'incline-treadmill-walk.mp4', 406),
  ('Indoor Cycling Spin', 'Cardio', 'indoor-cycling-spin.mp4', 407),
  ('Jump Rope', 'Cardio', 'jump-rope.mp4', 408),
  ('Jumping Jack', 'Cardio', 'jumping-jack.mp4', 409),
  ('Long Run', 'Cardio', 'long-run.mp4', 410),
  ('Mountain Climber', 'Cardio', 'mountain-climber.mp4', 411),
  ('Rowing Intervals', 'Cardio', 'rowing-intervals.mp4', 412),
  ('Rowing Machine Steady State', 'Cardio', 'rowing-machine-steady-state.mp4', 413),
  ('Rowing Sprint', 'Cardio', 'rowing-sprint.mp4', 414),
  ('Running Cool-Down', 'Cardio', 'running-cooldown.mp4', 415),
  ('Running Intervals', 'Cardio', 'running-intervals.mp4', 416),
  ('Shadow Boxing', 'Cardio', 'shadow-boxing.mp4', 417),
  ('SkiErg', 'Cardio', 'ski-erg.mp4', 418),
  ('Sled Pull', 'Cardio', 'sled-pull.mp4', 419),
  ('Sled Push', 'Cardio', 'sled-push.mp4', 420),
  ('Stair Climber', 'Cardio', 'stair-climber.mp4', 421),
  ('Steady State Ride', 'Cardio', 'steady-state-ride.mp4', 422),
  ('Swim Kick Drill', 'Cardio', 'swim-kick-drill.mp4', 423),
  ('Swim Pull Drill', 'Cardio', 'swim-pull-drill.mp4', 424),
  ('Swim Sprint Intervals', 'Cardio', 'swim-sprint-intervals.mp4', 425),
  ('Tempo Run', 'Cardio', 'tempo-run.mp4', 426),
  ('Trail Run', 'Cardio', 'trail-run.mp4', 427),
  ('Treadmill Run', 'Cardio', 'treadmill-run.mp4', 428),
  ('VersaClimber', 'Cardio', 'versaclimber.mp4', 429),
  ('Ab Stretch 1', 'Mobility', 'abdominals-stretch-variation-one.mp4', 430),
  ('Ab Stretch 2', 'Mobility', 'abdominals-stretch-variation-two.mp4', 431),
  ('Ab Stretch 3', 'Mobility', 'abdominals-stretch-variation-three.mp4', 432),
  ('Ab Stretch 4', 'Mobility', 'abdominals-stretch-variation-four.mp4', 433),
  ('Barbell Spinal Jefferson Curl', 'Mobility', 'barbell-spinal-jefferson-curl.mp4', 434),
  ('Bodyweight Spinal Jefferson Curl', 'Mobility', 'bodyweight-spinal-jefferson-curl.mp4', 435),
  ('Dead Hang', 'Mobility', 'dead-hang.mp4', 436),
  ('Dumbbell Spinal Jefferson Curl', 'Mobility', 'dumbbell-spinal-jefferson-curl.mp4', 437),
  ('Kettlebell Spinal Jefferson Curl', 'Mobility', 'kettlebell-spinal-jefferson-curl.mp4', 438)
) as v (name, category, file, sort_order)
where not exists (select 1 from public.exercises e where e.name = v.name);
